"""Initial migration

Revision ID: d419612ba5db
Revises: 
Create Date: 2026-07-10 22:09:00.042073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd419612ba5db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('cuenta_ircc', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('numero_pasaporte', sa.Text(), nullable=True),
    sa.Column('contrasena_cifrada', sa.Text(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('correo_electronico', sa.Text(), nullable=True),
    sa.Column('numero_pasaporte', sa.Text(), nullable=True),
    sa.Column('contrasena_cifrada', sa.Text(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_tramex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('id_solicitud', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('numero_pasaporte', sa.Text(), nullable=True),
    sa.Column('tramite', sa.Text(), nullable=True),
    sa.Column('cita', sa.Text(), nullable=True),
    sa.Column('correo_electronico', sa.Text(), nullable=True),
    sa.Column('contrasena_cifrada', sa.Text(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasaportes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('lugar_cita', sa.Text(), nullable=True),
    sa.Column('fecha_cita', sa.Date(), nullable=True),
    sa.Column('fecha_cita_original', sa.Text(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pasaportes')
    op.drop_table('master_tramex')
    op.drop_table('global_entry')
    op.drop_table('canada')
    # ### end Alembic commands ###
